<template>
  <paginate
    v-model="pages"
    :prev-text="'Prev'"
    :page-count="all"
    :page-range="3"
    :margin-pages="3"
    :next-text="'Next'"
    :container-class="'pagination'"
    :page-class="'page-item'"
    :link-class="'page-link'"
  >
  </paginate>
</template>

<script>
export default {
    name:"Pagination",
    data:function(){
        return{
            pages:3,
            all:0,
        }
    },
    props:{elements},
    beforeCreate:function(){
        this.all=this.elements
    },
}
